version: '3'
services: 
    web:
        environment:
            - CHOKIDAR_USEPOLLING=true
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        ports: 
            - "3000:3000"
        volumes: 
            - /app/node_modules
            - C:\Users\ugur.coruh\Desktop\react-app\frontend:/app
    tests:
        environment:
            - CHOKIDAR_USEPOLLING=true
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        volumes: 
            - /app/node_modules
            - C:\Users\ugur.coruh\Desktop\react-app\frontend:/app
        command: ["npm", "run", "test"]
        

